class IconsApp {
  IconsApp._();

  static const String logoApp = 'assets/icons/logo.svg';
  static const String logoSeller = 'assets/icons/logo_seller.svg';
  static const String email = 'assets/icons/email.svg';
  static const String password = 'assets/icons/password.svg';
  static const String questionMark = 'assets/icons/question_mark.svg';
  static const String vendorAccount = 'assets/icons/vendor_account.svg';
  static const String buyerAccount = 'assets/icons/buyer_account.svg';
  static const String mobile = 'assets/icons/mobile.svg';
  static const String person = 'assets/icons/person.svg';
  static const String id = 'assets/icons/id.svg';
  static const String commercialRegisterNumber =
      'assets/icons/commercial_register_number.svg';
  static const String buildingNumber = 'assets/icons/building_number.svg';
  static const String emirate = 'assets/icons/emirate.svg';
  static const String location = 'assets/icons/location.svg';
  static const String postalCode = 'assets/icons/postal_code.svg';
  static const String street = 'assets/icons/street.svg';
  static const String city = 'assets/icons/city.svg';
  static const String character = 'assets/icons/character.svg';
  static const String copy = 'assets/icons/copy.svg';
  static const String locationMini = 'assets/icons/location_mini.svg';
  static const String locationMap = 'assets/icons/location_map.svg';
  static const String distance = 'assets/icons/distance.svg';
  static const String stop = 'assets/icons/stop.svg';
  static const String backgroundCard = 'assets/icons/backgroundCard.svg';
  static const String homeOutline = 'assets/icons/home_outline.svg';
  static const String homeFill = 'assets/icons/home_fill.svg';
  static const String chatOutline = 'assets/icons/chat_outline.svg';
  static const String chatFill = 'assets/icons/chat_fill.svg';
  static const String offersSubmittedOutline =
      'assets/icons/offers_submitted_outline.svg';
  static const String offersSubmittedFill =
      'assets/icons/offers_submitted_fill.svg';
  static const String profileOutline = 'assets/icons/profile_outline.svg';
  static const String profileFill = 'assets/icons/profile_fill.svg';
  static const String edit = 'assets/icons/edit.svg';
  static const String remove = 'assets/icons/remove.svg';
  static const String fillScreen = 'assets/icons/fill_screen.svg';
  static const String cross = 'assets/icons/cross.svg';
  static const String check = 'assets/icons/check.svg';
  static const String carBody = 'assets/icons/car_body.svg';
  static const String carCategory = 'assets/icons/car_category.svg';
  static const String carColorInside = 'assets/icons/car_color_inside.svg';
  static const String carColorOutside = 'assets/icons/car_color_outside.svg';
  static const String carMechanic = 'assets/icons/car_mechanic.svg';
  static const String carName = 'assets/icons/car_name.svg';
  static const String carPrice = 'assets/icons/car_price.svg';
  static const String carSpeed = 'assets/icons/car_speed.svg';
  static const String carStatus = 'assets/icons/car_status.svg';
  static const String enginePower = 'assets/icons/engine_power.svg';
  static const String fuelType = 'assets/icons/fuel_type.svg';
  static const String image = 'assets/icons/image.svg';
  static const String info = 'assets/icons/info.svg';
  static const String regionalSpecifications =
      'assets/icons/regional_specifications.svg';
  static const String tradeMark = 'assets/icons/trade_mark.svg';
  static const String yearOfManufacture =
      'assets/icons/year_of_manufacture.svg';
  static const String car = 'assets/icons/car.svg';
  static const String exclamationMark = 'assets/icons/exclamation_mark.svg';
  static const String addNewCommunication =
      'assets/icons/add_new_communication.svg';
  static const String facebookOld = 'assets/icons/facebook_old.svg';
  static const String whatsapp = 'assets/icons/whatsapp.svg';
  static const String orangeCar = 'assets/icons/orange_car.svg';
  static const String chatting = 'assets/icons/chatting.svg';
  static const String favoriteFill = 'assets/icons/favorite_fill.svg';
  static const String favoriteOutline = 'assets/icons/favorite_outline.svg';
  static const String searchFill = 'assets/icons/search_fill.svg';
  static const String searchOutline = 'assets/icons/search_outline.svg';
  static const String notification = 'assets/icons/notification.svg';
  static const String filter = 'assets/icons/filter.svg';
  static const String call = 'assets/icons/call.svg';
  static const String facebook = 'assets/icons/facebook.svg';
  static const String google = 'assets/icons/google.svg';
  static const String logo = 'assets/icons/logo.svg';
  static const String twitter = 'assets/icons/twitter.svg';
  static const String price = 'assets/icons/price.svg';
  static const String bigCheck = 'assets/icons/big_check.svg';
  static const String trash = 'assets/icons/trash.svg';
  static const String resend = 'assets/icons/resend.svg';
  static const String hi = 'assets/icons/hi.svg';
  static const String background = 'assets/icons/background.svg';
  static const String editProfile = 'assets/icons/editprofile.svg';
  static const String profilePhone = 'assets/icons/prfile_phone.svg';
  static const String profileEmail = 'assets/icons/profile_email.svg';
  static const String addressIcon = 'assets/icons/address_icon.svg';
  static const String profileImages = 'assets/icons/profile_image.svg';
  static const String aboutUs = 'assets/icons/about_us.svg';
  static const String aboutApp = 'assets/icons/aboutApp.svg';
  static const String contactUs = 'assets/icons/contact_us.svg';
  static const String share = 'assets/icons/share.svg';
  static const String policy = 'assets/icons/policy.svg';
  static const String condations = 'assets/icons/condations.svg';
  static const String setting = 'assets/icons/setting.svg';
  static const String logout = 'assets/icons/logout.svg';
  static const String tabBar = 'assets/icons/tab_bar.svg';
  static const String editIcon = 'assets/icons/edit_icon.svg';
  static const String locationStore = 'assets/icons/location_store.svg';
}
