name: haraj
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # BASE
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.2.0
  http: ^0.13.6
  flutter_svg: ^2.0.5
  image_picker: ^1.0.2
  card_swiper: ^3.0.1
  share_plus: ^7.0.2
  internet_connection_checker: ^1.0.0+1
#  stream_transform: ^2.1.0
  json_serializable: ^6.6.2
  dartz: ^0.10.1
  device_info_plus: ^9.0.3
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.11
  flutter_html: any



  # STATE MANAGEMENT
  get: ^4.6.5
  expandable: ^5.0.1

  # DATABASE
  sqflite: ^2.2.8+4
  path: ^1.8.2
  path_provider: ^2.0.15

  # MAPS
  google_maps_flutter: ^2.1.12
  # permission_handler: ^10.0.0
  geolocator: ^9.0.1
  geocoding: ^2.0.4

  #FIREBASE
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.0.4
  firebase_storage: ^11.0.3
  firebase_messaging: ^14.0.4
  flutter_local_notifications: ^12.0.3


#  syncfusion_flutter_sliders: any
#  syncfusion_flutter_gauges: any
#  readmore: ^2.2.0
#  flutter_advanced_switch: ^3.0.1
#  expandable: ^5.0.1
#  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Regular.ttf
          weight: 300
        - asset: assets/fonts/Avenir-Medium.otf
          weight: 500
        - asset: assets/fonts/Avenir-Bold.otf
          weight: 800
#          style: italic
