name: haraj
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # BASE
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.2.0
  http: ^0.13.6
  flutter_svg: ^1.1.4
  image_picker: ^1.0.2
  carousel_slider: ^4.2.1
  share_plus: ^7.0.2


  # STATE MANAGEMENT
  get: ^4.6.5


  # DATABASE
  sqflite: ^2.2.8+4
  path: ^1.8.2
  path_provider: ^2.0.15

#  syncfusion_flutter_sliders: any
#  syncfusion_flutter_gauges: any
#  readmore: ^2.2.0
#  flutter_advanced_switch: ^3.0.1
#  expandable: ^5.0.1
#  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Regular.ttf
          weight: 300
        - asset: assets/fonts/Avenir-Medium.otf
          weight: 500
        - asset: assets/fonts/Avenir-Bold.otf
          weight: 800
#          style: italic
